const ADD_FILES = 'ADD_FILES';
const REMOVE_All_FILES = 'REMOVE_All_FILES';
const REMOVE_FILE = 'REMOVE_FILE';
const IS_MAX_FILES = 'IS_MAX_FILES';
const IS_LOADING = 'IS_LOADING';
const IS_UPLOAD_SUCCESS = 'IS_UPLOAD_SUCCESS';
const IS_SERVER_ERROR = 'IS_SERVER_ERROR';
const IS_AUTH = 'IS_AUTH';
const TOKEN = 'TOKEN';
const AUTH_ERROR = 'AUTH_ERROR';

export {
  ADD_FILES,
  REMOVE_All_FILES,
  REMOVE_FILE,
  IS_MAX_FILES,
  IS_LOADING,
  IS_UPLOAD_SUCCESS,
  IS_SERVER_ERROR,
  IS_AUTH,
  TOKEN,
  AUTH_ERROR
}
